import "../globals.css";
import { Navbar } from "./Components/Navbar";
import { Sidebar } from "./Components/Sidebar";

export const metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
        <body>
          <Navbar/>
          <main className="flex">
            <Sidebar/>
            {children}
          </main>
        </body>
    </html>
  )
}
