export const metadata = {
  title: 'Mujeres Mezcaleras de Michoacán',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  )
}
