import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
import { CartProvider } from './context/cart'
import ButtonCarrito from './Components/ButtonCarrito'
import { MezcalerasProvider } from './context/mezcalerasContext'
import { UsuariosProvider } from './context/usuariosContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mujeres Mezcaleras de Michoacán',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body> 
        <CartProvider>
          <Navbar />
          <UsuariosProvider>
            <MezcalerasProvider>
              {children}
            </MezcalerasProvider>
            </UsuariosProvider>
          <Footer />
          <ButtonCarrito />
        </CartProvider>
      </body>
    </html>
  )
}
